### ISSUE TITLE
Crashing homebridge since new firmwares

### ISSUE THREAD

**Issue by mensa84** [Adeptive/SoundTouch-NodeJS#11]
Hello,

I have a problem with homebridge-soundtouch. I think that is basing on SoundTouch-NodeJS, right?
That plugin is crashing since new firmware for SoundTouch 20 was released (FW 20.0.6)).

Log:

```
Nov 23 06:43:01 Server homebridge[28366]: /usr/lib/node_modules/homebridge-soundtouch/node_modules/soundtouch/api.js:67
Nov 23 06:43:01 Server homebridge[28366]:         var isAlive =  json.nowPlaying.source != SOURCES.STANDBY;
Nov 23 06:43:01 Server homebridge[28366]:                                        ^
Nov 23 06:43:01 Server homebridge[28366]: TypeError: Cannot read property 'source' of undefined
Nov 23 06:43:01 Server homebridge[28366]:     at /usr/lib/node_modules/homebridge-soundtouch/node_modules/soundtouch/api.js:67:40
Nov 23 06:43:01 Server homebridge[28366]:     at /usr/lib/node_modules/homebridge-soundtouch/node_modules/soundtouch/api.js:363:17
Nov 23 06:43:01 Server homebridge[28366]:     at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-soundtouch/node_modules/soundtouc                                                   h/utils/xmltojson.js:25:13)
Nov 23 06:43:01 Server homebridge[28366]:     at emitNone (events.js:111:20)
Nov 23 06:43:01 Server homebridge[28366]:     at IncomingMessage.emit (events.js:208:7)
Nov 23 06:43:01 Server homebridge[28366]:     at endReadableNT (_stream_readable.js:1064:12)
Nov 23 06:43:01 Server homebridge[28366]:     at _combinedTickCallback (internal/process/next_tick.js:139:11)
Nov 23 06:43:01 Server homebridge[28366]:     at process._tickCallback (internal/process/next_tick.js:181:9)
Nov 23 06:43:01 Server systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Nov 23 06:43:01 Server systemd[1]: homebridge.service: Unit entered failed state.
Nov 23 06:43:01 Server systemd[1]: homebridge.service: Failed with result 'exit-code'.
```

**Comment by theovassiliou** [comment]
I am also using SoundTouch-NodeJS but in addition to the homebridge module I am using it also standalone. I just checked with my systems (SA-4 and Soundtouch 20; FW 20.0.6) and the standalone version and cannot reproduce the problem.  The function where this happens is typically called on powerOn or powerOff. Is this where it happens, when you are using it via homebridge? @mensa84 is it possible to narrow down *when* the problem happens?
